#!/usr/bin/env bash
# =====================================================================
# Universal Convert - Linux installer
# =====================================================================
# Adds the "Convert With..." entry to:
#   - GNOME Files (Nautilus) scripts menu  -> ~/.local/share/nautilus/scripts
#   - KDE Dolphin  service menu            -> ~/.local/share/kservices5/ServiceMenus
# Both pass the FULL multi-selection to main.py in one invocation.
# An optional .desktop file adds menu entries on other desktops (double-click
# launcher). No admin rights required.
#
#   install:    bash installers/linux.sh
#   uninstall:  bash installers/linux.sh --uninstall
# =====================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
MAIN_PY="$PROJECT_DIR/main.py"

NAUTILUS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nautilus/scripts"
DOLPHIN_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/kservices5/ServiceMenus"
DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
NAUTILUS_SCRIPT="$NAUTILUS_DIR/Convert With..."
DOLPHIN_DESKTOP="$DOLPHIN_DIR/universal-convert.desktop"
LAUNCHER_DESKTOP="$DESKTOP_DIR/universal-convert.desktop"

info() { printf '\033[36m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m[OK]\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m[!!]\033[0m %s\n' "$*"; }
fail() { printf '  \033[31m[XX]\033[0m %s\n' "$*"; exit 1; }

if [[ "${1:-}" == "--uninstall" ]]; then
  info "Removing context menu entries..."
  rm -f "$NAUTILUS_SCRIPT" "$DOLPHIN_DESKTOP" "$LAUNCHER_DESKTOP"
  ok "Removed (config kept)."
  exit 0
fi

[[ "$(uname -s)" == "Linux" ]] || fail "This script is for Linux. You are on $(uname -s)."
[[ -f "$MAIN_PY" ]] || fail "main.py not found at $MAIN_PY"

# ------------------------------------------------------------ 1. python3
info "Looking for Python 3..."
PY3=""
if command -v python3 >/dev/null 2>&1; then
  PY3="$(command -v python3)"
elif command -v python >/dev/null 2>&1; then
  PY3="$(command -v python)"
fi
[[ -n "$PY3" ]] || fail "python3 not found. Install it with your package manager (e.g. sudo apt install python3 python3-pip python3-tk)."
ok "Python 3: $PY3"

"$PY3" -c 'import tkinter' 2>/dev/null \
  || warn "tkinter is missing - the dialog will not open. Install python3-tk."
"$PY3" -c 'import PIL' 2>/dev/null \
  || warn "Pillow is missing - run: $PY3 -m pip install --user Pillow"

# ------------------------------------------------------------ 2. pip deps
info "Checking Python packages..."
"$PY3" -m pip install --user --quiet pypdf PyMuPDF Pillow \
  || warn "pip install failed - see the message above."
ok "Dependencies processed."

# ------------------------------------------------------------ 3. LibreOffice
info "Checking LibreOffice..."
if command -v soffice >/dev/null 2>&1 || command -v libreoffice >/dev/null 2>&1; then
  ok "LibreOffice found."
else
  warn "LibreOffice not found - needed for Office/PDF document conversions."
  warn "Install it with your package manager, e.g.: sudo apt install libreoffice"
fi

# ------------------------------------------------------- 4. Nautilus script
info "Installing Nautilus (GNOME Files) script..."
mkdir -p "$NAUTILUS_DIR"
cat > "$NAUTILUS_SCRIPT" <<EOF
#!/usr/bin/env bash
# Generated by Universal Convert installer - passes the whole selection
# (as arguments) to the converter.
export PATH="/usr/local/bin:/usr/bin:/bin:\$PATH"
exec "$PY3" "$MAIN_PY" "\$@"
EOF
chmod +x "$NAUTILUS_SCRIPT"
ok "Installed: $NAUTILUS_SCRIPT"

# ------------------------------------------------------- 5. Dolphin menu
info "Installing KDE Dolphin service menu..."
mkdir -p "$DOLPHIN_DIR"
cat > "$DOLPHIN_DESKTOP" <<EOF
[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
MimeType=application/pdf;image/jpeg;image/png;image/webp;image/gif;image/bmp;image/tiff;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.openxmlformats-officedocument.presentationml.presentation;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;application/vnd.oasis.opendocument.text;application/vnd.oasis.opendocument.presentation;application/vnd.oasis.opendocument.spreadsheet;
Actions=universalConvert;
X-KDE-Priority=TopLevel

[Desktop Action universalConvert]
Name=Convert With...
Icon=convert
Exec=$PY3 "$MAIN_PY" %F
EOF
ok "Installed: $DOLPHIN_DESKTOP"

# ---------------------------------------------------- 6. generic launcher
info "Installing a .desktop launcher (for other file managers / menus)..."
mkdir -p "$DESKTOP_DIR"
cat > "$LAUNCHER_DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Universal Convert
Comment=Convert images, PDFs and Office documents
Exec=$PY3 "$MAIN_PY" %F
Icon=convert
Terminal=false
Categories=Utility;Graphics;
MimeType=application/pdf;image/jpeg;image/png;image/webp;image/gif;image/bmp;image/tiff;
EOF
ok "Installed: $LAUNCHER_DESKTOP"

# ------------------------------------------------------------- 7. refresh
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$DESKTOP_DIR" >/dev/null 2>&1 || true
fi
if command -v nautilus >/dev/null 2>&1; then
  warn "Restart Nautilus to see the new script:  nautilus -q"
fi

echo
info "Install complete."
echo "  GNOME Files: right-click -> Scripts -> 'Convert With...'"
echo "  Dolphin:     right-click -> Convert With..."
